name: lets-plot-docs
channels:
  - conda-forge
dependencies:
  - python=3.7
  - geopandas
  - jupyter_sphinx
  - matplotlib
  - numpy
  - pip
  - pypandoc
  - scipy
  - sphinx
  - sphinx-panels
  - sphinx-gallery
  - pip:
    - sphinx_bootstrap_theme